{
 "title": "Monitor Service HTTP traffic",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prometheus Uptime",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"localhost:9090\",job=\"prometheus\"})"
    }
   ]
  },
  { "title": "Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total HTTP request in last 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (max_over_time(http_server_requests_seconds_count[24h]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP request with status code is  200 or 300 in last 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_requests_seconds_count{status=~\"2..|3..\"}[24h]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP request with status code is  400 or 500 ni last 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_requests_seconds_count{status=~\"4..|5..\"}[24h]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total 404 errors HTTP request in last 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(uri) (max_over_time(http_server_requests_seconds_count{status=\"404\"}[24h]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(container_network_transmit_bytes_total{name=\"nistagram-infrastructure_nistagram-gateway_1\"} + container_network_receive_bytes_total{name=\"nistagram-infrastructure_nistagram-gateway_1\"}) / 1073741824 ",
     "legendFormat": "total trafic"
    }
   ]
  },
  {
   "title": "Unique visitors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "unique_user_counter_total", "legendFormat": "unique_visitors" }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}